"""Write `openapi.json`, and fail if it has drifted (AD-016).

The committed schema is the contract. A reviewer seeing a diff in it knows the
API changed; a reviewer seeing none knows it did not, and neither of those is
true if the file is regenerated by a step nobody reads. `just schema` writes it,
CI runs `--check`, and a change to a route that nobody exported turns into a red
build rather than an n8n workflow that breaks on the next deploy.

**Built from placeholder settings, never from the environment.** Generating the
schema must not need a Postgres DSN, an API key, or a reachable Chroma — CI has
none of them, and a schema that could only be produced on a configured host
would stop being checked. `build_app` constructs the object graph without
touching any of it; the lifespan handler is where connections happen, and it is
never entered here.

The provider is stubbed for the same reason: `_build_providers` refuses to start
without an API key, and the schema does not depend on which drivers exist.
"""

import argparse
import json
import sys
from pathlib import Path
from typing import Any

from ai_embeddings import EmbeddingModel, EmbeddingProvider, RawEmbeddings
from ai_embeddings.port import Purpose
from kb_api.config import KbApiSettings
from kb_api.main import build_app

__all__ = ["OPENAPI_PATH", "export", "main"]

OPENAPI_PATH = Path(__file__).resolve().parents[3] / "openapi.json"

_PLACEHOLDER_DSN = "postgresql+asyncpg://schema:schema@127.0.0.1:5432/schema"

_SCHEMA_VERSION = "0.1.0"
"""The version stamped into the document. Bumped deliberately, with the API."""


class _SchemaOnlyProvider(EmbeddingProvider):
    """Never called. It exists so the registry has something to resolve."""

    @property
    def model(self) -> EmbeddingModel:
        return EmbeddingModel(
            provider="openai",
            model_id="text-embedding-3-small",
            dimensions=1536,
            max_input_tokens=8191,
            max_batch_inputs=96,
        )

    def count_tokens(self, text: str) -> int:
        return len(text)

    async def _embed(self, texts: object, purpose: Purpose) -> RawEmbeddings:
        raise NotImplementedError("the schema export never embeds anything")


def schema() -> dict[str, Any]:
    """The OpenAPI document the running service would serve."""
    settings = KbApiSettings(
        # Pinned, not defaulted. `title` and `version` in the document come from
        # these, and `KbApiSettings` reads `.env` — so a developer whose local
        # file sets either would export a schema that differs from CI's and fail
        # the drift check for a reason that has nothing to do with the API.
        service_name="kb-api",
        service_version=_SCHEMA_VERSION,
        api_keys={"schema": "placeholder"},
        postgres={"dsn": _PLACEHOLDER_DSN},
        openai={"api_key": "placeholder"},
    )
    app = build_app(settings, providers={"openai": _SchemaOnlyProvider()})
    return app.openapi()


def export(path: Path = OPENAPI_PATH, *, check: bool = False) -> int:
    """Write the schema, or compare it. Returns a process exit code."""
    # Trailing newline and sorted keys so the file is diff-stable: an unsorted
    # dump reorders on a dependency upgrade and produces a diff that says the
    # API changed when it did not.
    rendered = json.dumps(schema(), indent=2, sort_keys=True) + "\n"

    if check:
        if not path.exists():
            print(f"{path} does not exist; run `just schema`", file=sys.stderr)
            return 1
        if path.read_text() != rendered:
            print(
                f"{path} is out of date; run `just schema` and commit the result",
                file=sys.stderr,
            )
            return 1
        return 0

    path.write_text(rendered)
    print(f"wrote {path}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the committed schema differs, instead of rewriting it",
    )
    parser.add_argument("--path", type=Path, default=OPENAPI_PATH)
    arguments = parser.parse_args()
    return export(arguments.path, check=arguments.check)


if __name__ == "__main__":
    raise SystemExit(main())
